# Generated by Django 5.2.9 on 2025-12-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='imagen_predeterminada.png', upload_to='articulos/'),
        ),
    ]
